# Generated by Django 5.0.3 on 2024-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_count',
            field=models.IntegerField(default=0),
        ),
    ]
