# Generated by Django 5.0.2 on 2024-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
